
<div class="actions-toolbar create-btn">
  <div class="primary">
    <button type="submit" class="action create primary" title="<?php  echo __('Create Ticket') ?>"><span><a href="<?php echo $this->getUrl("ticketingsystem/create"); ?>"><?php  echo __('Create') ?></a></span></button>
  </div>
</div>

<?php  $_gridrecords = $block->getCollection(); // get collection which we set in block class?>
<?php if ($_gridrecords && count($_gridrecords)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('Ticket #') ?></th>
                    <th scope="col" class="col category"><?php echo __('Category') ?></th>
                    <th scope="col" class="col subject"><?php echo __('Subject') ?></th>
                    <th scope="col" class="col status"><?php echo __('Status') ?></th>
                    <th scope="col" class="col priority"><?php echo __('Priority') ?></th>
                    <th scope="col" class="col date"><?php echo __('Created Date') ?></th>
                    <th scope="col" class="col ">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php $blockObj= $block->getLayout()->createBlock('Ktree\TicketingSystem\Block\Create'); ?>
                <?php  foreach ($_gridrecords as $_gridrecord) {
    ?>
                    <tr>
                        <td class="col id"><?php echo $_gridrecord->getTicketId() ?></td>
                        <td class="col category"><?php echo $blockObj->getCategories($_gridrecord->getCategory()); ?></td>
                        <td class="col subject"><?php echo $_gridrecord->getSubject(); ?></td>
                        <td class="col status"><?php echo $blockObj->getStatus($_gridrecord->getStatus()); ?></td>
                        <td class="col priority"><?php echo $blockObj->getPriorities($_gridrecord->getPriority()); ?></td>
                        <td class="col date"><?php echo $_gridrecord->getCreatedAt(); ?></td>
                    </tr>
                <?php
} ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.?></div>
    <?php endif ?>
    <?php else : ?>
        <div class="message info empty"><span><?php echo __('You have raised no tickets.'); ?></span></div>
    <?php endif ?>
